/**
 * A 3D mesh extracted from CT scan data, ready for GPU rendering.
 * 
 * Generated by tools/ct-processor/process_ct.py and consumed
 * by the WebGPU renderer in the dicom-model app. The format is the data contract between the Python processor and the TypeScript viewer; both sides must honor it
 */
export interface HeartMesh {
    /**
     * Interleaved vertex data in groups of 6 floats:
     * [x, y, z, nx, ny, nz, ...]
     * 
     * - x, y, z: vertex position in model space
     * 
     * - nx, ny, nz: surface normal at vertex (used for lighting)
     * 
     * Total vertex count = vertices.length / 6
     */
    vertices: number[];

    /**
     * Triangle indices into the vertices array. Every 3 consecutive indices form one triangle.
     * 
     * Total triangle count = indices.length / 3
     * 
     * Indices may exceed 65535, so consumers must use Uint32Array (not Uint16Array)
     * when uploading to GPU index buffers.
     */
    indices: number[];
}

import schema from './heart-mesh.schema.json';

/**
 * The JSON schema describing the HeartMesh wire format.
 * Use wwith a validator like Ajv to verify untrusted JSON before
 * treating it as a HeartMesh
 */

export const heartMeshSchema = schema;

import Ajv from 'ajv';

const ajv = new Ajv();
const validateHeartMesh = ajv.compile<HeartMesh>(schema);

/**
 * Parse and validate untrusted JSON as a HeartMesh.
 * 
 * Use this at I/O boundaries where data comes from outside the
 * type system (file reads, network responses, etc.) to guarantee
 * the runtime shape matches the compile-time type.
 * 
 * @throws Error if the data does not conform to the HeartMesh schema
 */

export function parseHeartMesh(data: unknown): HeartMesh {
    if (validateHeartMesh(data)) {
        return data;
    }
    const errorMessages = (validateHeartMesh.errors ?? [])
    .map((e) => `${e.instancePath || '<root>'}: ${e.message}`)
    .join('; ');
    throw new Error (`Invalid HeartMesh data: ${errorMessages}`);
}