server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    gzip_static on;

    gzip on;
    gzip_types application/javascript text/css application/json;
    gzip_min_length 1000;
    gzip_comp_level 6;
}